database:
  router: root:123456@tcp(0g-serving-broker-db:3306)/router?parseTime=true
event:
  routerAddr: ":8089"
interval:
  refundProcessor: 1
networks:
  ethereum0g:
    url: "https://evmrpc-testnet.0g.ai"
    chainID: 16600
    privateKeys:
      - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    transactionLimit: 1000000
    gasEstimationBuffer: 10000
zkProver:
  router: "zk-server:3000"
  requestLength: 40
presetService:
  providerAddress: "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  serviceName: "local-router-only"
