networks:
  ethereum0g:
    url: "https://evmrpc-testnet.0g.ai"
    chainID: 16600
    privateKeys:
      - 1111111111111111111111111111111111111111111111111111111111111111
    transactionLimit: 1000000
    gasEstimationBuffer: 10000
service:
  servingUrl: "<Serving_URL>"
  pricePerToken: 1
  quota:
    cpuCount: 8
    memory: 16
    storage: 10
    gpuType: "H200"
    gpuCount: 1
storageClient:
  indexerStandard: "https://indexer-storage-testnet-standard.0g.ai"
  indexerTurbo: "https://indexer-storage-testnet-turbo.0g.ai"
  uploadArgs:
    finalityRequired: true
    tags: "0x"
    expectedReplica: 1
    skipTx: false
    taskSize: 4
    fragmentSize: 4294967296
    routines: 4
logger:
  level: "debug"
  path: "/tmp/fine-tuning.log"
