contractAddress: 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9
database:
  router: root:123456@tcp(0g-serving-router-db:3306)/router?parseTime=true
event:
  routerAddr: ":8089"
interval:
  refundProcessor: 1
networks:
  ethereumHardhat:
    url: "http://192.168.1.103:8545/"
    chainID: 31337
    privateKeys:
      - 5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
    transactionLimit: 9500000
    gasEstimationBuffer: 0
  ethereum0g:
    url: "https://evmrpc-testnet.0g.ai"
    chainID: 16600
    privateKeys:
      - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    transactionLimit: 1000000
    gasEstimationBuffer: 10000
presetServices:
  providerAddress: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
  serviceName: "local-router-only"
